### ISSUE TITLE
Mino moves error

### ISSUE THREAD

**Issue by KanaSahoda** [KKKKK-55555/Javaris#7]
ミノの挙動について
・ミノa　＝操作可能、自動落下不可能
・ミノb　＝操作不可能、自動落下可能

・どちらも下で固定される
・同時には表示されない（操作を行うときのみミノbが表示される）

**Comment by shuodongWANG** [comment]
最初のミノが正しく動作している

**Comment by KKKKK-55555** [comment]
nextMinoがうまく反映されず、2個目以降のミノがミノaとミノbになる問題ですが、おそらく操作を担っているinitControl()内でGameThread内のminoを扱っていないためだと考えられます。対策も考えたのでわかり次第また追加します。

**Comment by KKKKK-55555** [comment]
# Resolve
## 方針
- initControl()の中で常にGameThread上での最新の（現在の）minoを取得するようにする
- 最新のGameThreadインスタンスをAppクラス内で使えるようにする
- GameThreadクラスに、現在のminoを返すメソッドを作成する

## 具体的な変更
- Appクラスのフィールド
  - App()コンストラクタで作成するGameThreadインスタンスをAppクラスのフィールドとして定義する
    - GameThread gt;
- Appクラスのコンストラクタ
  - this.gt = new GameThread();
  - gt.start()
- GameThreadクラスにゲッター追加
  - public void getMinoNow()
- AppクラスのinitControl()メソッド
  - minoとしていた部分をすべてgt.getMinoNow()に変更した
